name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

  


    steps:
    - name: Build
      run: |
        mkdir mything
        cd mything
        env >>envtest.txt        


    - uses: actions/checkout@v3
    - name: Build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mything
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
